name: CI/CD with SonarCloud Gate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: CI - Build, Test & SonarCloud
    runs-on: ubuntu-latest
    outputs:
      quality_gate_status: ${{ steps.qualitygate.outputs.quality_gate_status }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test -- --watchAll=false --ci

      - name: Build
        run: CI=false npm run build --if-present

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v2.0.2
        with:
          args: >
            -Dsonar.projectKey=12ff12_ci-cd
            -Dsonar.organization=12ff12
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: SonarCloud Quality Gate
        id: qualitygate
        uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
        with:
          scanMetadataReportFile: .scannerwork/report-task.txt
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  cd:
    name: Deploy to Vercel
    needs: ci
    if: ${{ needs.ci.outputs.quality_gate_status == 'passed' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: .
          github-comment: true
          prod: true
