name: CI/CD with SonarCloud Gate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: CI - Build, Test & SonarCloud
    runs-on: ubuntu-latest
    outputs:
      quality_gate_status: ${{ steps.qualitygate.outputs.quality-gate-status }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test -- --watchAll=false --ci

      - name: Build
        run: npm run build --if-present

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v2.0.2
        env:
          SONAR_HOST_URL: https://sonarcloud.io
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=12ff12_ci-cd
            -Dsonar.organization=12ff12

      - name: Wait for Quality Gate
        id: qualitygate
        uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Debug Quality Gate Output
        run: echo "Status: ${{ steps.qualitygate.outputs.quality-gate-status }}"

  cd:
    name: Deploy to Vercel
    needs: ci
    if: ${{ needs.ci.outputs.quality_gate_status == 'OK' && github.event_name == 'push' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Debug CI Outputs
        run: |
          echo "CI Job Outputs: ${{ toJSON(needs.ci.outputs) }}"
          echo "Quality Gate Status: ${{ needs.ci.outputs.quality_gate_status }}"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm ci

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: .
          github-comment: true
          prod: true
