name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies   # ✅ Added this so react-scripts is available
        run: npm install

      - name: Run tests
        run: npm test -- --watchAll=false --ci   # ✅ safer test command

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: success()   # <--- this makes sure deploy only runs if tests succeed
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to production
        run: echo "🚀 Deploying..."
